server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/platform
    username: platform
    password: platform
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: redis
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8081
management:
  tracing:
    sampling:
      probability: 1.0
